//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InitDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;hoten&quot;:&quot;Isaiah Grigoriscu&quot;,&quot;ngaysinh&quot;:&quot;1993-12-23&quot;,&quot;diachi&quot;:&quot;40 Rusk Crossing&quot;,&quot;email&quot;:&quot;igrigoriscu0@blogspot.com&quot;,&quot;loaidocgia&quot;:&quot;X&quot;,&quot;ngaylapthe&quot;:&quot;2016-03-03&quot;,&quot;ngayhethan&quot;:&quot;2016-09-03&quot;,&quot;tongno&quot;:69000},
        ///{&quot;hoten&quot;:&quot;Leonie Kleisle&quot;,&quot;ngaysinh&quot;:&quot;1993-05-02&quot;,&quot;diachi&quot;:&quot;73449 Monica Point&quot;,&quot;email&quot;:&quot;lkleisle1@who.int&quot;,&quot;loaidocgia&quot;:&quot;X&quot;,&quot;ngaylapthe&quot;:&quot;2017-01-11&quot;,&quot;ngayhethan&quot;:&quot;2017-07-11&quot;,&quot;tongno&quot;:71000},
        ///{&quot;hoten&quot;:&quot;Shayne Fuster&quot;,&quot;ngaysinh&quot;:&quot;1982-05-23&quot;,&quot;diachi&quot;:&quot;503 Heath Pass&quot;,&quot;email&quot;:&quot;sfuster2@example.com&quot;,&quot;loaid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string docgia {
            get {
                return ResourceManager.GetString("docgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;tensach&quot;:&quot;Phalaropus lobatus&quot;,&quot;theloai&quot;:&quot;A&quot;,&quot;tacgia&quot;:&quot;Patrice Labusch&quot;,&quot;namxb&quot;:2015,&quot;nxb&quot;:&quot;nhà xuất bản Reynolds Group&quot;,&quot;ngaynhapsach&quot;:&quot;2015-10-04&quot;,&quot;trigia&quot;:19000},
        ///{&quot;tensach&quot;:&quot;Geochelone elegans&quot;,&quot;theloai&quot;:&quot;A&quot;,&quot;tacgia&quot;:&quot;Corri Caen&quot;,&quot;namxb&quot;:2012,&quot;nxb&quot;:&quot;nhà xuất bản Hauck-Armstrong&quot;,&quot;ngaynhapsach&quot;:&quot;2015-11-20&quot;,&quot;trigia&quot;:47000},
        ///{&quot;tensach&quot;:&quot;Ramphastos tucanus&quot;,&quot;theloai&quot;:&quot;C&quot;,&quot;tacgia&quot;:&quot;Gratiana Ketcher&quot;,&quot;namxb&quot;:2015,&quot;nxb&quot;:&quot;nhà xuất bản Lemke Group&quot;,&quot;ngaynhapsach&quot;:&quot;2010-06-21&quot;,&quot;trigia&quot;:35000},
        ///{&quot;tensach&quot;:&quot;C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sach {
            get {
                return ResourceManager.GetString("sach", resourceCulture);
            }
        }
    }
}
